### ISSUE TITLE
Native spell checker needs reboot before loading new learned words

### ISSUE THREAD

**Issue by RichardLitt** [wooorm/osx-learn#2]
I am having issues with some apps reading from my LocalDictionary in High Sierra. Specifically, iA Writer and Atom don't seem to accept 'journalled' as a correct spelling, although it is in my local dictionary. 

I'm curious if others are having this problem. I'm logging this here because I'm wondering if the name of the file has changed since the upgrade, and I think that you're the most likely to know.

**Comment by RichardLitt** [comment]
![1678907-o_1973v2pu61a51biekhg13jmc4jh-thumbnail-full](https://user-images.githubusercontent.com/910753/37158039-6165e336-22b8-11e8-9fb7-5184b2674702.jpg)

I've spent some time tinkering on this. I think the issue is not that it doesn't read from the file, but rather that adding to the file doesn't automatically refresh the system's spellchecker anymore immediately. A full restart did the trick, for me (putting the computer to sleep didn't). 

So, what would be great is if we could find a way to automatically refresh the spell checker after adding the word.

**Comment by RichardLitt** [comment]
The offending culprit is `/System/Library/Services/AppleSpell.service/Contents/MacOS/AppleSpell`. @wooorm Do you know an easy way to restart this service using a Node package? If so, we should add a subroutine to restart this service after adding words in. That should solve the problem I'm having.

**Comment by RichardLitt** [comment]
Ugh. Restarting the process works:

```
launchctl stop com.apple.applespell
launchctl start com.apple.applespell
```

But then Atom or iA Writer needs to be reopened for it to take effect, too. What a hassle.

**Comment by wooorm** [comment]
Ahh thanks for checking this out Richard!

The script restarts applespell on L81:

https://github.com/wooorm/osx-learn/blob/53e005f19d56591400b5a2120886efd2797ff550/osx-learn.sh#L81

So I guess we can add the lines you posted there. I’m apparently still on the old macOS, so I can check it if that’ll keep working with your additions!

For Atom / iA Writer: did that use to work? 🤔

**Comment by RichardLitt** [comment]
So, that line _should_ restart AppleSpell, but it doesn't work on it's own. I just tested by using learn, and then restarting Atom. The offending word was still misspelled. However, when I used `launchctl` as above, and _then_ restarted Atom, the word was now registered as spelled correctly. 

This means a couple of things: First, that `killall -e AppleSpell` is unnecessary. Secondly, that OSX High Sierra may be doing things differently. And thirdly, that we need to find some way to refresh our app's spellchecker files, too. I suspect that they're using a process and not locally loading the spell checker - I may be wrong, though. I have a feeling that there should be a programmatic way to force refresh without rebooting each program that uses LocalDictionary.

**Comment by wooorm** [comment]
~~Ah, I can confirm that `killall -e AppleSpell &> /dev/null` did not fix a lot.~~

EDIT: working in the wrong nvm...

**Comment by RichardLitt** [comment]
Update: with the lines added above, you do not need to restart Atom. You simply need to refresh the spell checker for the current file. You can do this by closing and reopening the particular document you're working on - or, by writing another word. Simply saving the file is not enough to actually refresh the spell checker, which may have been an error I've been making in my tests above. 

I think you say the same thing above?

Shall we simply add that line to the script? I think that should solve this issue for me.

**Comment by RichardLitt** [comment]
Or perhaps we should include both? This may just be an issue for fixing Spellchecker on High Sierra.

**Comment by wooorm** [comment]
Alright, so I tested with your two lines instead of killall, plus the `uniq` one, and now it seems to work, in textedit.

* write fooo, see it get a red underline
* do `learn fooo` in terminal, and in textedit add a blank line and then fooo, no red underline

So: new changes work in future text. But red underlines don’t disappear. They are still red, but not seen my apple spell anymore (<kbd>CMD+:</kbd> or <kbd>CMD+;</kbd> don’t work anymore).

However, <kbd>CMD+A</kbd>, <kbd>CMD+X</kbd> and <kbd>CMD+:V</kbd> does remove underlines!

**Comment by wooorm** [comment]
wow: <img width="460" alt="screen shot 2018-03-08 at 17 04 53" src="https://user-images.githubusercontent.com/944406/37161401-de3b7b7a-22f2-11e8-8094-5c757213ba9c.png">

**Comment by RichardLitt** [comment]
Whoa, what are those commands?

**Comment by wooorm** [comment]
it’s <kbd><kbd>nested kbd’s!</kbd></kbd>
